language: python
cache:
  - apt
  - pip
sudo: false
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
script:
  - flake8 bayegram tests bayegramserver
  - pylint bayegram tests bayegramserver
